---
site_name: "LAB-21216: Cisco phone 9800 series: Setup, customize and manage" # This must begin with the session ID, e.g. LABXXX-1234 This is my Cisco Live Lab
site_url: https://webexcc-sa.github.io/LAB-21216/
site_description: "LAB-21216: Cisco phone 9800 series: Setup, customize and manage" # must be same as "site_name"
site_author: Nehal Mehta
copyright: Copyright &copy; 2026 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
  repo: "https://github.com/WebexCC-SA/LAB-21216.git"
  site_event: test
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - template_assets/js/newLoad.js
  - template_assets/js/setInfo.js
  - template_assets/js/webexAccess.js
  - template_assets/js/vendor/qrcode-generator-2.0.4.js
  - template_assets/js/devicefxActivation.js
plugins:
  - search
  - macros
  # - with-pdf:
  #     cover_title: LABXXX-1234
  #     cover_subtitle: My famous WebexOne Lab
  #     cover_logo: template_assets/wx1Splash_new.gif
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - sane_lists
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Welcome: welcome.md
  - Lab:
      - Overview: overview.md
      #- Lab 1 - Getting Started: lab1_getting_started.md
      - Lab 1 - Setup: lab-1-setup.md
      - Lab 2 - Action button: lab-2-configure-the-action-button-using-webex-calling.md
      - Lab 3 - Favorite button: lab-3-configure-the-favorite-button-on-webex-calling.md
      - Lab 4 - Always use the multi-line layout: lab-4-always-use-the-multi-line-layout.md
      - Lab 5 - User added speed dials: lab-5-user-added-speed-dials.md
      - Lab 6 - Pagination: lab-6-pagination-on-cisco-desk-phone-9851-and-9861.md
      - Lab 7 - Customize the settings menu: lab-7-customize-the-settings-menu.md
      - Lab 8 - Custom wallpaper: lab-8-custom-wallpaper-on-cisco-9800-series-phones.md
      - Lab 9 - Custom ringtone: lab-9-custom-ringtone.md
      - Lab 10 - Smart audio: lab-10-smart-audio-in-webex-calling.md
      - Lab 11 - Closed captions: lab-11-closed-captions.md
      - Lab 12 - Device statuses on Control Hub: lab-12-control-hub-statuses.md
      - Learn more: learn-more.md
  #- Topologies: topologies.md
  #- How to use this guide:
      #- Setting up and using the tool:
        #- Initial Setup: howToUse/initialSetup.md
        #- Using the tool after the initial setup: howToUse/postInitial.md
        #- Publishing your changes: howToUse/syncChanges.md
      #- Useful Tools and Resources: howToUse/usefulTools.md
      #- Importing from Word (docx): howToUse/importingFromWord.md
      #- Styling and Advanced Features:
        #- Custom Features: howToUse/customFeatures.md
        #- Custom Admonitions: howToUse/admonition.md
      #- Looking for Inspiration: howToUse/previousEventLabs.md
      #- Before the Event: howToUse/beforeTheEvent.md